------------------------------------------------------------------------------------------------------
--  Lua script for importing a .csv lookup table into MMWave Studio, to simulate non-linear chirps. --
--                                  Written by: Chris Carolus                                       --
--                                  Supplemented by lookup.m                                        --
------------------------------------------------------------------------------------------------------


--Globals. Generally only have to change this unless you want to extend/add functionality.

IDLE_TIME = 0           -- Idle time of ADC. Keep at 0.
ADC_START = 1.5         -- Start time of ADC [μs].
ADC_SAMPLES = 128       -- Amount of samples that the ADC will take. Advised to keep it at an 2^n number.
--MAX_SAMPLES = 4096      -- Absolute maximum ADC samples. Code may be extended to calculate necessary sample amount for bandwidth, but N.I.
--MAX_SAMPLERATE = 60000  -- Absolute maximum ADC sample rate. N.I.
SAMPLE_RATE = 30000     -- Sample rate of ADC [kHz].

FRAME_AMT = 48          -- Amount of frames the radar will take.
CHIRP_AMT = 128         -- Amount of chirps per frame. For total number of chirps, multiply by #chirpArray[1] (or amount of different configurations).
PERIODICITTY = 10       -- Frame duration [ms].

RX_GAIN = 30            -- Antenna gain [dB].

                        -- Path to lookput table generated by MATLAB script. Replace by actual path name.
LOOKUP_FILE_PATH = "C:\\PATH\\TO\\FILE\\HERE.csv"

-- Lookup table structure:
------------------------------------------------------------------
--  <Start Frequency>   <Slope frequency>   <Chirp duration>    --
------------------------------------------------------------------


-- LL functions --
    --  debug   --
function nl()
    WriteToLog("\n")
end

function PrintArray(array, dimension)
    
    if dimension == 2 then
        for i = 1, #array, 1 do
            for j = 1, #array[1], 1 do
                WriteToLog(array[i][j]) nl()
            end
        
        end  
    end
    if dimension == 1 then
        for i = 1, #array, 1 do
            WriteToLog(array[i]) nl()
        end
    end
    
end

    -- actual functionality --

function GHzToMHz(array)
    for i = 1, #array do
        array[i] = array[i] * 1000
    end
end

function LoadLookup(filePath)
    local a_startFreq = {}
    local a_rampFreq = {}
    local stepTime = {}
    local chirpTable = {a_startFreq, a_rampFreq, stepTime}
    
    WriteToLog("Opening file in ") WriteToLog(filePath, "blue") nl()

    local file = assert(io.open(filePath, "r"), "no such file or directory\n")

    local lines = {}
    
    for line in file:lines() do

        local values = {}
        for value in line:gmatch("[^,]+") do
            table.insert(values, value)
        end

        table.insert(lines, values)
    end

    file:close()

    for i = 1, #lines[1], 1 do
        table.insert(a_startFreq, tonumber(lines[1][i]))
        table.insert(a_rampFreq, tonumber(lines[2][i]))
        table.insert(stepTime, tonumber(lines[3][i]))
    end

    WriteToLog("finished saving all in loop\n")

    chirpTable[1] = a_startFreq
    chirpTable[2] = a_rampFreq
    chirpTable[3] = stepTime

    return chirpTable
end


    -- HL functions --
function ProfileConfiguration(filePath)
    local chirpTable = LoadLookup(filePath)

    GHzToMHz(chirpTable[2]) -- for easier calculation.

    WriteToLog("Loading profile configs\n")

    for i = 0, #chirpTable[1]-1, 1 do
        ar1.ProfileConfig(i, chirpTable[1][i+1], IDLE_TIME, ADC_START, chirpTable[3][i+1], 0, 0, 0, 0, 0, 0, 0, 0, chirpTable[2][i+1], 0, ADC_SAMPLES, SAMPLE_RATE, 2216755200, 0, RX_GAIN, 0, 0, 0)

        WriteToLog("iteration ") WriteToLog(i, "blue") nl()

    end

    WriteToLog("Loading chirp configs\n")

    for i = 0, #chirpTable[1]-1, 1 do
        if i+1<=#chirpTable[1]-1 then
            ar1.ChirpConfig(i, i+1, i, 0, 0, 0, 0, 1, 1, 0, 0)
        else
            ar1.ChirpConfig(i, #chirpTable[1]-1, i, 0, 0, 0, 0, 1, 1, 0, 0)
        end

        WriteToLog("iteration ") WriteToLog(i, "blue") nl()
    end

    WriteToLog("Configuring frame\n")

    ar1.FrameConfig(0, #chirpTable[1]-1, FRAME_AMT, CHIRP_AMT, PERIODICITTY, 0, 1)

    return 0
end

    --------------------
    --script execution--
    --------------------
WriteToLog("Starting profile configuration...\n", "green")
ProfileConfiguration(LOOKUP_FILE_PATH)
WriteToLog("Finished execution!\n", "green")
